### ISSUE TITLE
Some bugs, shortcomings and suggestions

### ISSUE THREAD

**Issue by Kixot14** [NoChanceSD/PvPManager#89] opened 2015-12-09 22:48 UTC
1. Plugin WGFlyFlag (http://www.curse.com/bukkit-plugins/minecraft/worldguard-fly-flag#t1:description). If player use this fly, and hit someone, fly will be disabled with combat. But he can immediately enable fly again, with double-space.

2. Plugin FlightPack (http://www.curse.com/bukkit-plugins/minecraft/flightpack)
A problem similar to WGFlyFlag. If player equip flight-item and toggled in combat, fly will be disabled, but after re-equip this flight-item, he can immediately reuse fly with double space. Very sad, cause it's very cool plugin :[

3. Fly don't turned back automatically, when combat off

4. [suggestion] Can you add supplement to option [Punishments -> Money Penalty] ?
With condition: 
• When player dont have enough money, he died and drop items from list. 
• Or he just go to minus balance [not recomended minus, cause may be bugged with other plugins]. • Or his debt write in data and send him message about that. And after reload will be check and charged... [i think this great!]

5. Missing message for [Kill Abuse -> Respawn Protection]. Attacker don't know why he can't attack another player after he respawn.

6. [Kill Abuse] canceled after relogin

7. Missing loc. for /tag command [u are not in combat; U are in combat at X sec...]

8. [suggestion] Can you add possibility to remove some messages from messages.properties to prevent spam?? As if i delete this message, it just dont be sended.

9. Im not sure, but looks like [Tagged In Combat -> NameTag Prefix]
and [PvP Toggle -> NameTags -> Prefix On|Off] don't work or work not correctly.

I use latest dev-build (# 190)
hope you anwer for my questions soon, and say me what you can fix and what can not. Cause i don't know what i must do next...

**Comment by NoChanceSD** [comment] 2015-12-11 14:17
1 and 2 don't seem an issue to me, seems like something those plugins should solve.
3. Works as intended, why should fly be turned back on?
4. Will think about it, might do something.
5. Might add message but didn't really want to spam player chat
6. What do you mean with this?
7. Also don't get this one, are you talking about the message being configurable? I already added that in the premium version.
8. Yes, this will be added in premium. Not sure if free will get it as well.
9. Don't work how? Seem fine on my tests.

**Comment by Kixot14** [comment] 2015-12-13 05:16
I think 1, 2 and 3 it's also your problem, cause CombatTag and CombatLog have fix for that. (except # 3 in CombatLog)

6. I mean if u have Kill Abuse -> Max Kills: 10, and player kill another player 9 times, after relog he can again do 9 kills Commands on Abuse don't be actual

**Comment by NoChanceSD** [comment] 2016-02-04 22:22
So quite a few of this suggestions got added, i'm closing it.

**Closed by NoChanceSD** 2016-02-04 22:22 UTC
