### ISSUE TITLE
does not show the bar

### ISSUE THREAD

**Issue by pepixiko** [NoChanceSD/PvPManager#215] opened 2020-08-06 14:27 UTC
[16:25:09] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to PvPManager v3.7.16
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:762) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityPlayer.die(EntityPlayer.java:559) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1234) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:745) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:712) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityHuman.attack(EntityHuman.java:1064) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.EntityPlayer.attack(EntityPlayer.java:1655) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1915) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at me.NoChance.PvPManager.Player.EcoPlayer.depositMoney(EcoPlayer.java:27) ~[?:?]
        at me.NoChance.PvPManager.Player.EcoPlayer.giveReward(EcoPlayer.java:53) ~[?:?]
        at me.NoChance.PvPManager.Listeners.PlayerListener.onPlayerDeath(PlayerListener.java:107) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        ... 25 more

**Comment by NoChanceSD** [comment] 2020-08-09 20:34
This was caused by having no economy plugin, should be fixed now.

**Closed by NoChanceSD** 2020-08-09 20:34 UTC
