### ISSUE TITLE
user file broken after restart

### ISSUE THREAD

**Issue by EvilOlaf** [NoChanceSD/PvPManager#117] opened 2016-06-02 16:21 UTC
```
[05:29:29] [Server thread/INFO]: [PvPManager] Enabling PvPManager v3.1.8
[05:29:29] [Server thread/ERROR]: [PvPManager] Error loading users file! Error:
[05:29:29] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: org.yaml.snakeyaml.error.YAMLException: Unexpected referential mapping structure. Node: <org.yaml.snakeyaml.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.yaml.snake
yaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=newbie_timeleft)>; value=337363561 }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=newbie)>; value=117753389 }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, valu
e=pvpstatus)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=pvpstatus)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:bool, value=true)>> }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml
.org,2002:str, value=toggletime)>; value=<NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=toggletime)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:int, value=1464718911225)>> })>
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
[05:29:29] [Server thread/WARN]:        at me.NoChance.PvPManager.Managers.ConfigManager.loadUsersFile(ConfigManager.java:98)
[05:29:29] [Server thread/WARN]:        at me.NoChance.PvPManager.Managers.ConfigManager.<init>(ConfigManager.java:37)
[05:29:29] [Server thread/WARN]:        at me.NoChance.PvPManager.PvPManager.loadFiles(PvPManager.java:69)
[05:29:29] [Server thread/WARN]:        at me.NoChance.PvPManager.PvPManager.onEnable(PvPManager.java:47)
[05:29:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[05:29:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[05:29:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:29:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[05:29:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[05:29:29] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[05:29:29] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[05:29:29] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[05:29:29] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[05:29:29] [Server thread/WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[05:29:29] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:745)
[05:29:29] [Server thread/WARN]: Caused by: org.yaml.snakeyaml.error.YAMLException: Unexpected referential mapping structure. Node: <org.yaml.snakeyaml.nodes.MappingNode (tag=tag:yaml.org,2002:map, values={ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:
str, value=newbie_timeleft)>; value=337363561 }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=newbie)>; value=117753389 }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=pvpstatus)>; value=<NodeTuple keyNode=<org.
yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=pvpstatus)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:bool, value=true)>> }{ key=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=toggletime)>; value=<Nod
eTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=toggletime)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:int, value=1464718911225)>> })>
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:23)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:373)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:147)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:354)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:489)
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[05:29:29] [Server thread/WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[05:29:29] [Server thread/WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[05:29:29] [Server thread/WARN]:        ... 17 more
```

Has never been manually modified.
PM 3.1.8

**Comment by EvilOlaf** [comment] 2016-06-16 16:33
Downgraded to build 226 and seems to work again.

**Comment by NoChanceSD** [comment] 2016-06-16 17:38
I can't reproduce this issue but should get fixed by https://github.com/NoChanceSD/PvPManager/commit/ec0d2255987cb1f98ccaf7afbb951592f9b26beb
Users file will be reset though.

**Comment by NoChanceSD** [comment] 2016-07-14 17:34
It's fixed i believe, tell me if not.

**Closed by NoChanceSD** 2016-07-14 17:34 UTC
